name: CI

on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Solve all
      run: dotnet run -c Release --no-build -- all
      working-directory: ./AdventOfCode
